/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ali's Laptop
 */
public class addDoc extends javax.swing.JFrame {

    String selected;
    Admin a1;
    public addDoc(){}
    public addDoc(Admin a1) {
        initComponents();
        this.a1=a1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        specializationsbox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        idfield = new javax.swing.JTextField();
        ssnfield = new javax.swing.JTextField();
        fnamefiled = new javax.swing.JTextField();
        lnamefield = new javax.swing.JTextField();
        agefiled = new javax.swing.JTextField();
        phonefiled = new javax.swing.JTextField();
        dobfiled = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();
        genderfield = new javax.swing.JTextField();
        nationalityfield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        roomnumberfield = new javax.swing.JTextField();
        feesfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Zurich Cn BT", 1, 23)); // NOI18N
        jLabel1.setText("Add Doctor in a Specific Specialization");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Select Specialization");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 84, -1, -1));

        specializationsbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        specializationsbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "orthepedic", "Opthamology" }));
        specializationsbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specializationsboxActionPerformed(evt);
            }
        });
        getContentPane().add(specializationsbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 135, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("SSN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 155, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("First Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Last Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 225, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Age");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Phone Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 295, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Date Of Birth");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 365, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Gender");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Nationality");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 435, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Email");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Room Number");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 503, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Fees");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 538, -1, -1));

        idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfieldActionPerformed(evt);
            }
        });
        idfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idfieldKeyTyped(evt);
            }
        });
        getContentPane().add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 135, -1));

        ssnfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ssnfieldKeyTyped(evt);
            }
        });
        getContentPane().add(ssnfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 135, -1));
        getContentPane().add(fnamefiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 135, -1));
        getContentPane().add(lnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 135, -1));

        agefiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agefiledKeyTyped(evt);
            }
        });
        getContentPane().add(agefiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 135, -1));

        phonefiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonefiledKeyTyped(evt);
            }
        });
        getContentPane().add(phonefiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 135, -1));
        getContentPane().add(dobfiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 135, -1));
        getContentPane().add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 135, -1));
        getContentPane().add(genderfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 135, -1));
        getContentPane().add(nationalityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 135, -1));
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 135, -1));
        getContentPane().add(roomnumberfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 135, -1));

        feesfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                feesfieldKeyTyped(evt);
            }
        });
        getContentPane().add(feesfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 135, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 578, -1, -1));

        jButton2.setFont(new java.awt.Font("Zurich Cn BT", 0, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 589, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic/vertical .jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void specializationsboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specializationsboxActionPerformed
        selected=specializationsbox.getSelectedItem().toString();
        
    }//GEN-LAST:event_specializationsboxActionPerformed

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try{
            selected=specializationsbox.getSelectedItem().toString();
            int id=Integer.parseInt(idfield.getText());
            int ssn=Integer.parseInt(ssnfield.getText());
            String fname=fnamefiled.getText();
            String lname=lnamefield.getText();
            int age=Integer.parseInt(agefiled.getText());
            String phonenumber=phonefiled.getText();
            String dob=dobfiled.getText();
            String address=addressfield.getText();
            String gender=genderfield.getText();
            String nationality=nationalityfield.getText();
            String email=emailfield.getText();
            String roomnum=roomnumberfield.getText();
            double fees=Double.parseDouble(feesfield.getText());
            arraylists.arr3.add(new Doctor(selected,  roomnum, fees, ssn,  id,  fname,  lname,  age,  phonenumber,  gender,  dob,  address,  nationality,  email));
            JOptionPane.showMessageDialog(null, "New Doctor with id"+" "+id+" "+"has been added successfully.");
           }
           catch(Exception e){
            JOptionPane.showMessageDialog(null, "please enter all the data");
           
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminMenu1 a=new AdminMenu1(a1);
        a.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void idfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idfieldKeyTyped
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE )){
            evt.consume();}
    }//GEN-LAST:event_idfieldKeyTyped

    private void ssnfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssnfieldKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE )){
            evt.consume();}
    }//GEN-LAST:event_ssnfieldKeyTyped

    private void agefiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agefiledKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE )){
            evt.consume();}
    }//GEN-LAST:event_agefiledKeyTyped

    private void phonefiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonefiledKeyTyped
 char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE )){
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_phonefiledKeyTyped

    private void feesfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feesfieldKeyTyped
 char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE )){
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_feesfieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressfield;
    private javax.swing.JTextField agefiled;
    private javax.swing.JTextField dobfiled;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField feesfield;
    private javax.swing.JTextField fnamefiled;
    private javax.swing.JTextField genderfield;
    private javax.swing.JTextField idfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lnamefield;
    private javax.swing.JTextField nationalityfield;
    private javax.swing.JTextField phonefiled;
    private javax.swing.JTextField roomnumberfield;
    private javax.swing.JComboBox<String> specializationsbox;
    private javax.swing.JTextField ssnfield;
    // End of variables declaration//GEN-END:variables
}
