/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

import clinic.PatientMenu1;
import clinic.arraylists;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CancelReservation extends javax.swing.JFrame {

    /**
     * Creates new form CancelReservation
     */
  Patient p1;
    public CancelReservation(){}
    public CancelReservation(Patient p1) {
        initComponents();
        this.p1=p1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Ridd = new javax.swing.JTextField();
        Cancell = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Enter Your  ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, -1));
        getContentPane().add(Ridd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 140, -1));

        Cancell.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cancell.setText("Cancel");
        Cancell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancellActionPerformed(evt);
            }
        });
        getContentPane().add(Cancell, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 120, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Enter Your Reservation ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 230, -1));

        idd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddActionPerformed(evt);
            }
        });
        idd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iddKeyTyped(evt);
            }
        });
        getContentPane().add(idd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 140, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Zurich Cn BT", 1, 36)); // NOI18N
        jLabel3.setText("Cancel Appoinment");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 350, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic/backkkk.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancellActionPerformed
        try{    
        int IDD=Integer.parseInt(idd.getText()); 
            int Rid = Integer.parseInt(Ridd.getText()); 
             for(int i=0;i<arraylists.arr.size();i++){
                    if(arraylists.arr.get(i).getID()==IDD){
                       for (int ii=0;ii<arraylists.r1.size();ii++) {
        if(arraylists.r1.get(ii).reservation_num==Rid){
            for(int j=0;j<arraylists.arr8.size();j++){
            if(arraylists.arr8.get(j).d1.ID==arraylists.r1.get(ii).Doctor_ID){
            arraylists.arr8.get(j).avalible=true;
            arraylists.r1.remove(ii);
            JOptionPane.showMessageDialog(null, "Your Reservation has been Cancelled successfully");
            MakeReservation.reservation_num--;
        
            
            }
            }
            
        
        }
                       }
                    }
             }
        }
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null, "Invalid Reservation ID");        
                }
        
        
        
                        
    }//GEN-LAST:event_CancellActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      PatientMenu1 m = new PatientMenu1(p1);
       m.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void iddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_iddActionPerformed

    private void iddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iddKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE )){
            evt.consume();}
    }//GEN-LAST:event_iddKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancell;
    private javax.swing.JTextField Ridd;
    private javax.swing.JTextField idd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
