/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

import clinic.Doctor;

/**
 *
 * @author zezoy
 */
public class Doctormenu1 extends javax.swing.JFrame {

    /**
     * Creates new form Doctormenu1
     */
    static public Doctor d1;
    public Doctormenu1(){}
    public Doctormenu1(Doctor d1) {
        initComponents();
        this.d1=d1;
        doc_name.setText(d1.firstName+" "+d1.lastName);
        Doc_id.setText(""+d1.ID);
        Doc_s.setText(d1.Specialization);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        doc_name = new javax.swing.JTextField();
        Doc_id = new javax.swing.JTextField();
        Doc_s = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Update_timeslot = new javax.swing.JButton();
        View_Timeslot = new javax.swing.JButton();
        Create_Order = new javax.swing.JButton();
        Update_Feess = new javax.swing.JButton();
        View_Income = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Doctor Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Doctor ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Specialization");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        getContentPane().add(doc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 131, 27));
        getContentPane().add(Doc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 131, 27));
        getContentPane().add(Doc_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 131, 27));

        jLabel4.setFont(new java.awt.Font("Zurich Cn BT", 1, 36)); // NOI18N
        jLabel4.setText("Doctor Page");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 48, -1, -1));

        Update_timeslot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update_timeslot.setText("Update Timeslot");
        Update_timeslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_timeslotActionPerformed(evt);
            }
        });
        getContentPane().add(Update_timeslot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 30));

        View_Timeslot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_Timeslot.setText("View Timeslot");
        View_Timeslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_TimeslotActionPerformed(evt);
            }
        });
        getContentPane().add(View_Timeslot, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, 30));

        Create_Order.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Create_Order.setText("Create Order");
        Create_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_OrderActionPerformed(evt);
            }
        });
        getContentPane().add(Create_Order, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, 30));

        Update_Feess.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update_Feess.setText("Update Fees");
        Update_Feess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_FeessActionPerformed(evt);
            }
        });
        getContentPane().add(Update_Feess, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, 30));

        View_Income.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        View_Income.setText("View Income");
        View_Income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_IncomeActionPerformed(evt);
            }
        });
        getContentPane().add(View_Income, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Back to login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic/backkkk.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Update_timeslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_timeslotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Update_timeslotActionPerformed

    private void View_TimeslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_TimeslotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_View_TimeslotActionPerformed

    private void Create_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_OrderActionPerformed
        // TODO add your handling code here:
        
        Createorder s =new Createorder(d1);
                    s.setVisible(true);
                    setVisible(false);
       
    }//GEN-LAST:event_Create_OrderActionPerformed

    private void Update_FeessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_FeessActionPerformed
        // TODO add your handling code here:
         Update_Fees s =new Update_Fees(d1);
                    s.setVisible(true);
                    setVisible(false);
        
    }//GEN-LAST:event_Update_FeessActionPerformed

    private void View_IncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_IncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_View_IncomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Login_Page a= new Login_Page();
       a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctormenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctormenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctormenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctormenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctormenu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create_Order;
    private javax.swing.JTextField Doc_id;
    private javax.swing.JTextField Doc_s;
    private javax.swing.JButton Update_Feess;
    private javax.swing.JButton Update_timeslot;
    private javax.swing.JButton View_Income;
    private javax.swing.JButton View_Timeslot;
    private javax.swing.JTextField doc_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
