/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

import javax.swing.JOptionPane;

/**
 *
 * @author Ali's Laptop
 */
public class Login_Page extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Login_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userfield = new javax.swing.JTextField();
        adminselect = new javax.swing.JRadioButton();
        doctorselect = new javax.swing.JRadioButton();
        patientselect = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        passfield = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        nurseselect = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Zurich Cn BT", 1, 36)); // NOI18N
        jLabel1.setText("Login Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfieldActionPerformed(evt);
            }
        });
        getContentPane().add(userfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 266, -1));

        buttonGroup2.add(adminselect);
        adminselect.setText("Admin");
        adminselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminselectActionPerformed(evt);
            }
        });
        getContentPane().add(adminselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 70, -1));

        buttonGroup2.add(doctorselect);
        doctorselect.setText("Doctor");
        doctorselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorselectActionPerformed(evt);
            }
        });
        getContentPane().add(doctorselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 70, 20));

        buttonGroup2.add(patientselect);
        patientselect.setText("Patient");
        getContentPane().add(patientselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 70, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic/Login.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 165, 47));
        getContentPane().add(passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 266, -1));

        jButton2.setText("I'm A new Patient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, 20));

        buttonGroup2.add(nurseselect);
        nurseselect.setText("Nurse");
        nurseselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurseselectActionPerformed(evt);
            }
        });
        getContentPane().add(nurseselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 70, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic/backkkk.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    private void adminselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminselectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean test=false;
        String username=userfield.getText();
        char[] pass=passfield.getPassword();
        String Password= String.copyValueOf(pass);
        if(!adminselect.isSelected()&&!patientselect.isSelected()&&!doctorselect.isSelected()&&!nurseselect.isSelected())
        JOptionPane.showMessageDialog(null, "Nothing is Selected , Please select one of the choices");
        else if(adminselect.isSelected()){

            for(int i=0;i<arraylists.useradmin.size();i++){
                if((arraylists.useradmin.get(i).username == null ? username == null : arraylists.useradmin.get(i).username.equals(username))&&(arraylists.useradmin.get(i).Password == null ? Password == null : arraylists.useradmin.get(i).Password.equals(Password))){
                    if("Modifing".equals(arraylists.useradmin.get(i).a1.getAdmin_field())){
                        AdminMenu1 m1=new AdminMenu1(arraylists.useradmin.get(i).a1);

                        if("Male".equals(arraylists.arr4.get(i).Gender))
                        JOptionPane.showMessageDialog(null, "Welcomee "+"mr." +arraylists.useradmin.get(i).a1.firstName+ " "+arraylists.useradmin.get(i).a1.lastName);
                        else if("Female".equals(arraylists.arr4.get(i).Gender))
                        JOptionPane.showMessageDialog(null, "Welcomee "+"ms." +arraylists.useradmin.get(i).a1.firstName+ " "+arraylists.useradmin.get(i).a1.lastName);
                        m1.setVisible(true);
                        setVisible(false);
                        test=true;

                    }
                    else if("Viewing".equals(arraylists.useradmin.get(i).a1.getAdmin_field())){
                        AdminMenu2 m1=new AdminMenu2(arraylists.useradmin.get(i).a1);
                        if("Male".equals(arraylists.arr4.get(i).Gender))
                        JOptionPane.showMessageDialog(null, "Welcomee "+"mr." +arraylists.useradmin.get(i).a1.firstName+ " "+arraylists.useradmin.get(i).a1.lastName);

                        else if("Female".equals(arraylists.arr4.get(i).Gender))
                        JOptionPane.showMessageDialog(null, "Welcomee "+"ms." +arraylists.useradmin.get(i).a1.firstName+ " "+arraylists.useradmin.get(i).a1.lastName);
                        m1.setVisible(true);
                        setVisible(false);
                        test=true;

                    }

                }
            }
            if(test==false){
                for(int j=0;j<arraylists.useradmin.size();j++){
                    if((arraylists.useradmin.get(j).username == null ? username != null : !arraylists.useradmin.get(j).username.equals(username))||(arraylists.useradmin.get(j).Password == null ? Password != null : !arraylists.useradmin.get(j).Password.equals(Password))){
                        JOptionPane.showMessageDialog(null, "Wrong input");
                        break;
                    }
                }
            }
        }
        else if(doctorselect.isSelected()){
            for(int i=0;i<arraylists.userdoc.size();i++){
                if((arraylists.userdoc.get(i).username == null ? username == null : arraylists.userdoc.get(i).username.equals(username))&&(arraylists.useradmin.get(i).Password == null ? Password == null : arraylists.userdoc.get(i).Password.equals(Password))){
                 JOptionPane.showMessageDialog(null, "Welcomee");
                    Doctormenu1 s =new Doctormenu1(arraylists.userdoc.get(i).d1);
                    s.setVisible(true);
                    setVisible(false);
                }
            }
            for(int j=0;j<arraylists.userdoc.size();j++){
                if((arraylists.userdoc.get(j).username == null ? username != null : !arraylists.userdoc.get(j).username.equals(username))||(arraylists.userdoc.get(j).Password == null ? Password != null : !arraylists.userdoc.get(j).Password.equals(Password))){
                    JOptionPane.showMessageDialog(null, "Wrong input");
                    break;
                }
            }
        }
        else if(patientselect.isSelected()){
            for(int i=0;i<arraylists.userpatient.size();i++){
                if((arraylists.userpatient.get(i).username == null ? username == null : arraylists.userpatient.get(i).username.equals(username))&&(arraylists.userpatient.get(i).Password == null ? Password == null : arraylists.userpatient.get(i).Password.equals(Password))){
                    JOptionPane.showMessageDialog(null, "Welcomee");
                    PatientMenu1 s =new PatientMenu1(arraylists.userpatient.get(i).p1);
                    s.setVisible(true);
                    setVisible(false);
                }
            }
            for(int j=0;j<arraylists.userpatient.size();j++){
                if((arraylists.userpatient.get(j).username == null ? username != null : !arraylists.userpatient.get(j).username.equals(username))||(arraylists.userpatient.get(j).Password == null ? Password != null : !arraylists.userpatient.get(j).Password.equals(Password))){
                    JOptionPane.showMessageDialog(null, "Wrong input");
                    break;
                }
            }
        }
        else if(nurseselect.isSelected()){
            for(int i=0;i<arraylists.usernurse.size();i++){
                if((arraylists.usernurse.get(i).username == null ? username == null : arraylists.usernurse.get(i).username.equals(username))&&(arraylists.usernurse.get(i).Password == null ? Password == null : arraylists.usernurse.get(i).Password.equals(Password))){
                    JOptionPane.showMessageDialog(null, "Welcomee");
                    nurse_menu s =new  nurse_menu(arraylists.usernurse.get(i).n1);
                    s.setVisible(true);
                    setVisible(false);
                }
            }
            for(int j=0;j<arraylists.usernurse.size();j++){
                if((arraylists.usernurse.get(j).username == null ? username != null : !arraylists.usernurse.get(j).username.equals(username))||(arraylists.usernurse.get(j).Password == null ? Password != null : !arraylists.usernurse.get(j).Password.equals(Password))){
                    JOptionPane.showMessageDialog(null, "Wrong input");
                    break;
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void doctorselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorselectActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       P_SignUpForm a=new P_SignUpForm();
       a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nurseselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurseselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nurseselectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminselect;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton doctorselect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton nurseselect;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JRadioButton patientselect;
    private javax.swing.JTextField userfield;
    // End of variables declaration//GEN-END:variables
}
