/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;
import clinic.PatientMenu1;
import clinic.arraylists;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class MakeReservation extends javax.swing.JFrame {

  static int reservation_num=0;
    Patient p1;
    int id;
    public MakeReservation(){}
    public MakeReservation(Patient p1) {
        initComponents();
        this.p1=p1;
        
        R_id.setText(""+p1.ID);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        specbox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        doctorbox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        timebox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        bookButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        R_id = new javax.swing.JTextField();
        Rdate = new javax.swing.JTextField();
        disease = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Zurich Cn BT", 1, 36)); // NOI18N
        jLabel11.setText("Schedule Appointment");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 118, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Patient Disease");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 104, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Reservation Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        specbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        specbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "orthepedic", "Opthamology" }));
        specbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specboxActionPerformed(evt);
            }
        });
        getContentPane().add(specbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 135, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Select a Specialization");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        doctorbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        doctorbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorboxActionPerformed(evt);
            }
        });
        getContentPane().add(doctorbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 135, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Select a Doctor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        timebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeboxActionPerformed(evt);
            }
        });
        getContentPane().add(timebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 135, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Select a timeslot");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        bookButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookButton.setText("Book");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 110, 40));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 26, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 34, -1));

        R_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_idActionPerformed(evt);
            }
        });
        R_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                R_idKeyTyped(evt);
            }
        });
        getContentPane().add(R_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 96, -1));
        getContentPane().add(Rdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 96, -1));

        disease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseaseActionPerformed(evt);
            }
        });
        getContentPane().add(disease, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 96, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic/backkkk.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void specboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specboxActionPerformed
        String selected;
        String namee ;  
        selected=specbox.getSelectedItem().toString();
        
    if( "orthepedic".equals(selected)){
        doctorbox.removeAllItems();
        for(int ii =0;ii<arraylists.arr3.size();ii++){
        if("orthepedic".equals(arraylists.arr3.get(ii).Specialization)){
            namee= arraylists.arr3.get(ii).ID+" "+arraylists.arr3.get(ii).firstName + " " + arraylists.arr3.get(ii).lastName;
            doctorbox.addItem(namee);   
            
        }
        }
    
         }
        else if("Opthamology".equals(selected)){
        doctorbox.removeAllItems();
        for(int ii =0;ii<arraylists.arr3.size();ii++){
        if("Opthamology".equals(arraylists.arr3.get(ii).Specialization)){
      
            namee= arraylists.arr3.get(ii).ID+" "+arraylists.arr3.get(ii).firstName + " " + arraylists.arr3.get(ii).lastName;
            doctorbox.addItem(namee); 
                
        }
        
        
        }
    
        }
    
   
    }//GEN-LAST:event_specboxActionPerformed

    private void R_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_idActionPerformed

    private void diseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diseaseActionPerformed

    private void doctorboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorboxActionPerformed
       try{
        String selected=doctorbox.getSelectedItem().toString();
        int spacepos= selected.indexOf(" ");
        id=Integer.parseInt(selected.substring(0, spacepos));
      
    timebox.removeAllItems();
    for(int i=0;i<arraylists.arr8.size();i++){
                  
                  if(id==arraylists.arr8.get(i).d1.ID){
                      if (arraylists.arr8.get(i).avalible==true) {   
                          timebox.addItem(arraylists.arr8.get(i).date);
                      }
                    
                  }
         }   
       }
       catch(Exception e){
       
       }
 
 
        
    }//GEN-LAST:event_doctorboxActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         PatientMenu1 m = new PatientMenu1(p1);
       m.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        
        Patient p=new Patient();
        for(int i=0;i<arraylists.arr.size();i++){
        if(p1.ID==arraylists.arr.get(i).ID){
        p=arraylists.arr.get(i);
        }
        }
                  Doctor d=new Doctor();
                  for(int i=0;i<arraylists.arr3.size();i++){
                  if(id==arraylists.arr3.get(i).ID){
                  d=arraylists.arr3.get(i);
                  }
                  }
                  
                       reservation_num++;
          
         
         String pd=disease.getText();
         
         
        Reservation temp=new Reservation();
         temp.setPatientDisease(pd);
         int PID=p.getID();
         int DID=d.getID();
         String Dspec=d.getSpecialization();
       String Dname=d.getFirstName()+" "+d.getLastName();
       for(int i=0;i<arraylists.arr8.size();i++){
       if((arraylists.arr8.get(i).date == null ? timebox.getSelectedItem().toString() == null : arraylists.arr8.get(i).date.equals(timebox.getSelectedItem().toString()))&&arraylists.arr8.get(i).d1.ID==d.ID){
       arraylists.arr8.get(i).avalible=false;
       temp.t1=arraylists.arr8.get(i);
       }
       }
       
       
       temp.setDoctor_ID(DID);
       temp.setD1(d);
       temp.setP1(p);
       temp.setDoctor_Name(Dname);
       temp.setDoctor_Name(Dname);
       temp.setReservation_num(reservation_num);
       temp.date=Rdate.getText();
        JOptionPane.showMessageDialog(null, "Your Reservation ID is: "+ " " + reservation_num);
       arraylists.r1.add(temp); 
       
    }//GEN-LAST:event_bookButtonActionPerformed

    private void timeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeboxActionPerformed

    private void R_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_R_idKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE )){
            evt.consume();}
    }//GEN-LAST:event_R_idKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField R_id;
    private javax.swing.JTextField Rdate;
    private javax.swing.JButton bookButton;
    private javax.swing.JTextField disease;
    private javax.swing.JComboBox<String> doctorbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> specbox;
    private javax.swing.JComboBox<String> timebox;
    // End of variables declaration//GEN-END:variables
        }