/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

import clinic.EditPatientinfo;
import clinic.MakeReservation;
import clinic.Patient;
import clinic.Patient;
import clinic.ViewReservation;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sarah's Laptop
 */




public class PatientMenu1 extends javax.swing.JFrame {

    
    Patient p1;
    public PatientMenu1(){}
     public PatientMenu1(Patient p1) {
         initComponents();
         this.p1=p1;
    }
    

        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        EditAccButton = new javax.swing.JButton();
        ModifyAppButton = new javax.swing.JButton();
        CancelAppButton = new javax.swing.JButton();
        ScheduleAppButton = new javax.swing.JButton();
        ViewAppButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditAccButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EditAccButton.setText("Edit Account");
        EditAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAccButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EditAccButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ModifyAppButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ModifyAppButton.setText("Modify Appointment");
        ModifyAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyAppButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ModifyAppButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 270, 50));

        CancelAppButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelAppButton.setText("Cancel Appointment");
        CancelAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelAppButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelAppButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 270, 50));

        ScheduleAppButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ScheduleAppButton.setText("Schedule Appointment");
        ScheduleAppButton.setPreferredSize(new java.awt.Dimension(270, 53));
        ScheduleAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleAppButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ScheduleAppButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));
        ScheduleAppButton.getAccessibleContext().setAccessibleDescription("");

        ViewAppButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewAppButton.setText("View all Appointments");
        ViewAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAppButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ViewAppButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 270, 50));

        jLabel1.setFont(new java.awt.Font("Zurich Cn BT", 1, 36)); // NOI18N
        jLabel1.setText("Patient Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Back to Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic/backkkk.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifyAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyAppButtonActionPerformed
         EditReservation e = new EditReservation(p1);
       e.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ModifyAppButtonActionPerformed

    private void ViewAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAppButtonActionPerformed
        ViewReservation v = new ViewReservation(p1);
       v.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ViewAppButtonActionPerformed

    private void ScheduleAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleAppButtonActionPerformed
        MakeReservation r = new MakeReservation(p1);
       r.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ScheduleAppButtonActionPerformed

    private void CancelAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelAppButtonActionPerformed
         CancelReservation c = new CancelReservation(p1);
       c.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_CancelAppButtonActionPerformed

    private void EditAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAccButtonActionPerformed
       EditPatientinfo e = new EditPatientinfo(p1);
       e.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_EditAccButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Login_Page a=new Login_Page();
       a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientMenu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientMenu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelAppButton;
    private javax.swing.JButton EditAccButton;
    private javax.swing.JButton ModifyAppButton;
    private javax.swing.JButton ScheduleAppButton;
    private javax.swing.JButton ViewAppButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
