/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ali's Laptop
 */
public class TotalRevenueTable extends javax.swing.JFrame {

    Admin a1;
     
     int row=0;
     int col=0;
     double total_revenues=0;
    public TotalRevenueTable(){}
    public TotalRevenueTable(Admin a1) {
        
        initComponents();
        this.a1=a1;
        int count=0;
        if(!arraylists.r1.isEmpty()) {
       for(int i=0;i<arraylists.arr3.size();i++){
            count=0;
            for(int j=0;j<arraylists.r1.size();j++){
            if(arraylists.r1.get(j).Doctor_ID==arraylists.arr3.get(i).ID)
             count++;  
            }
            
            
            total_revenues+=(double) (count*arraylists.arr3.get(i).fees);
            String id= String.valueOf(arraylists.arr3.get(i).ID);
            String Name=arraylists.arr3.get(i).firstName+" "+arraylists.arr3.get(i).lastName;
            String numreservation=String.valueOf(count);
            String fees=String.valueOf(count*arraylists.arr3.get(i).fees);
            String salary=String.valueOf(arraylists.arr3.get(i).income);
            String data[]={id,numreservation,Name,fees,salary};
            
            DefaultTableModel revenuetable=(DefaultTableModel) revenue.getModel();
            
            revenuetable.addRow(data);
        }
        totrevenue.setText(""+total_revenues);
       }
       else
           JOptionPane.showMessageDialog(null, "There is no reservations yet!!");
        for(int i=0;i<arraylists.arr3.size();i++){
            count=0;
          
            
            
            total_revenues+=(double) (count*arraylists.arr3.get(i).fees);
            String id= String.valueOf(arraylists.arr3.get(i).ID);
            String Name=arraylists.arr3.get(i).firstName+" "+arraylists.arr3.get(i).lastName;
            String numreservation=String.valueOf(count);
            String fees=String.valueOf(count*arraylists.arr3.get(i).fees);
            String salary=String.valueOf(arraylists.arr3.get(i).income);
            String data[]={id,numreservation,Name,fees,salary};
            
            DefaultTableModel revenuetable=(DefaultTableModel) revenue.getModel();
            
            revenuetable.addRow(data);
        }
        totrevenue.setText(""+total_revenues);
           
        
      
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        revenue = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        totrevenue = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        revenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor ID", "Number of Reservations", "Doctor Name", "Doctor Fees", "Doctor Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(revenue);
        if (revenue.getColumnModel().getColumnCount() > 0) {
            revenue.getColumnModel().getColumn(0).setResizable(false);
            revenue.getColumnModel().getColumn(1).setResizable(false);
            revenue.getColumnModel().getColumn(2).setResizable(false);
            revenue.getColumnModel().getColumn(3).setResizable(false);
            revenue.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, 537, 256));

        jScrollPane1.setViewportView(totrevenue);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 362, 154, -1));

        jLabel1.setText("Total Revenue is :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 370, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Zurich Cn BT", 1, 24)); // NOI18N
        jLabel2.setText("Total Revenes Report");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 45, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic/reportrevenue.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       AdminMenu2 a =new AdminMenu2(a1);
       a.setVisible(true);
        setVisible(false);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TotalRevenueTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TotalRevenueTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TotalRevenueTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TotalRevenueTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TotalRevenueTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable revenue;
    private javax.swing.JTextPane totrevenue;
    // End of variables declaration//GEN-END:variables
}
