/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinic;

import clinic.Doctor;
import clinic.arraylists;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author zezoy
 */
public class Update_Fees extends javax.swing.JFrame {

   Doctor d1;
   public Update_Fees(){}
    public Update_Fees(Doctor d1) {
        initComponents();
        this.d1=d1;
        ID_TextField.setText(""+d1.ID);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID_TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fees_TextField = new javax.swing.JTextField();
        confirme2 = new javax.swing.JButton();
        Back1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Zurich Cn BT", 1, 36)); // NOI18N
        jLabel1.setText("Update Fees");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 48, 185, 46));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Doctor ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 81, 20));

        ID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_TextFieldActionPerformed(evt);
            }
        });
        ID_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ID_TextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(ID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 157, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("New Fees");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        fees_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fees_TextFieldActionPerformed(evt);
            }
        });
        fees_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fees_TextFieldKeyTyped(evt);
            }
        });
        getContentPane().add(fees_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 157, 30));

        confirme2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirme2.setText("Confirm");
        confirme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirme2ActionPerformed(evt);
            }
        });
        getContentPane().add(confirme2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 116, 39));

        Back1.setText("Back");
        Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1ActionPerformed(evt);
            }
        });
        getContentPane().add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinic/backkkk.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_TextFieldActionPerformed

    private void fees_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fees_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fees_TextFieldActionPerformed

    private void confirme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirme2ActionPerformed
        // TODO add your handling code here:
          int id=Integer.parseInt(ID_TextField.getText());
          double fees= Double.parseDouble(fees_TextField.getText());
          for(int i=0;i<arraylists.arr3.size();i++){
      if(arraylists.arr3.get(i).ID==id){
           int db=JOptionPane.YES_NO_OPTION;
        int ds=JOptionPane.showConfirmDialog(this,"Update Fees", "Update",db);
        if (ds==0){
        JOptionPane.showMessageDialog(this,arraylists.arr3.get(i).fees,"old fees",2);
            JOptionPane.showMessageDialog(this,fees,"new fees",2);
        } 
      }
          }
    }//GEN-LAST:event_confirme2ActionPerformed

    private void Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1ActionPerformed
        // TODO add your handling code here:
        Doctormenu1 s =new Doctormenu1(d1);
                    s.setVisible(true);
                    setVisible(false);
    }//GEN-LAST:event_Back1ActionPerformed

    private void ID_TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ID_TextFieldKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE )){
        evt.consume();
        }
    }//GEN-LAST:event_ID_TextFieldKeyTyped

    private void fees_TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fees_TextFieldKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c== KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE )){
        evt.consume();
        }
    }//GEN-LAST:event_fees_TextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Fees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1;
    private javax.swing.JTextField ID_TextField;
    private javax.swing.JButton confirme2;
    private javax.swing.JTextField fees_TextField;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
